using UnityEngine;
using System.Collections;

public class UnitySpawnpoint : MonoBehaviour
{
    public void Start()
    {

    }
    public bool test;
}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               